def majorversion = ''
pipeline {
    agent  any 
    environment {
        CI = 'true'
    }
    stages {
        stage('Build') {
            steps {
                sh 'npm install'
            }
        }
        stage('Test') {
            steps {
                sh './jenkins/scripts/test.sh'
            }
        }

        //   stage('mycheck') {
        //      steps {
        //      sh '''#!/bin/bash
        //         majorversion=`grep version package.json | cut -c  15-17` 
        //         echo $majorversion
        //          mkdir  -p mama/test/$majorversion
        //       '''
        //      }
        //   }
        
           stage('mycheck2') {
              steps {
              script {
                 majorversion = sh(returnStdout: true, script:  "grep version package.json | cut -c  15-17")
                } 
              
              }
           }

             stage('checkoutput') {
              steps {
                   echo 'hello this is ${majorversion}'
                   sh "mkdir papa/timalo/${majorversion}"

              }
           }
      //  stage('Deliver') {
      //      steps {
      //          sh './jenkins/scripts/deliver.sh'
     //           input message: 'Finished using the web site? (Click "Proceed" to continue)'
     //           sh './jenkins/scripts/kill.sh'
     //       }
     //   }
    }
}
