pipeline {
    agent  any 
    environment {
        CI = 'true'
    }
    stages {
        stage('Build') {
            steps {
                sh 'npm install'
            }
        }
        stage('Test') {
            steps {
                sh './jenkins/scripts/test.sh'
            }
        }

           stage('mycheck') {
              steps {
                sh 'majorversion=`grep version package.json | cut -c  15-17` '
                sh 'echo `$majorversion`'
                sh 'mkdir -p mama/test/`$majorversion`'
              }
           }
      //  stage('Deliver') {
      //      steps {
      //          sh './jenkins/scripts/deliver.sh'
     //           input message: 'Finished using the web site? (Click "Proceed" to continue)'
     //           sh './jenkins/scripts/kill.sh'
     //       }
     //   }
    }
}
